// FIREBASE REGISTRATION: BORROWED, NOT YET THE DRIVER APP'S OWN.
//
// These values are the customer app's registration in the same Firebase
// project (kasieats-34391). They work: the project, the Auth backend and the
// API that verifies the tokens are all the same, and Auth is the only Firebase
// product this app uses.
//
// What they are not is this app's own registration, so before a release build
// the driver app needs registering in the Firebase console and this file
// regenerating:
//
//     cd apps/driver && flutterfire configure --project=kasieats-34391
//
// That writes the driver app's own appId per platform, which is what
// Crashlytics, Analytics and any API-key restriction key off. Until then, an
// Android release would carry an appId whose package name does not match
// com.lokshineats.lokshineats_driver.

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF-9ZByQqRSykNdEjFKOEwErsV_MWBEy0',
    appId: '1:741301128340:web:4837774d16c47668c5b881',
    messagingSenderId: '741301128340',
    projectId: 'kasieats-34391',
    authDomain: 'kasieats-34391.firebaseapp.com',
    storageBucket: 'kasieats-34391.firebasestorage.app',
    measurementId: 'G-8JX4VCNK3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoMsFgRrg1wY1dg_svarxx0uA7SE_fvmY',
    appId: '1:741301128340:android:ebc83bc142eecd66c5b881',
    messagingSenderId: '741301128340',
    projectId: 'kasieats-34391',
    storageBucket: 'kasieats-34391.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC05mO_3TDLkqltmMBCmyNgLCiIvU9rPRw',
    appId: '1:741301128340:ios:b5988f842a91bb83c5b881',
    messagingSenderId: '741301128340',
    projectId: 'kasieats-34391',
    storageBucket: 'kasieats-34391.firebasestorage.app',
    iosBundleId: 'com.lokshineats.lokshineatsCustomer',
  );
}
